# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.srcs/sources_1/ip/system_clk_creator/system_clk_creator.xci
# IP: The module: 'system_clk_creator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.srcs/sources_1/ip/system_clk_creator/system_clk_creator.xci
# IP: The module: 'system_clk_creator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dracho/Downloads/OneChannelTest/OneChannelTest/OneChannelTest.gen/sources_1/ip/system_clk_creator/system_clk_creator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_creator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
