
###### USER_CLOCK defines ########
## ISE Constraints (Daniel's implementation IOSTANDRARD HSTLI_DCI)
## Check again, if UltraScale board is used, no need for the VC707
set_property PACKAGE_PIN AJ32 [get_ports USER_CLOCK]
set_property IOSTANDARD LVCMOS18 [get_ports USER_CLOCK]


###### LVDS clock works ########
set_property PACKAGE_PIN E19 [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property PACKAGE_PIN E18 [get_ports SYSCLK_N]
set_property IOSTANDARD LVDS [get_ports SYSCLK_N]

create_clock -period 5.000 -name SYSCLK_P -waveform {0.000 2.500} [get_ports SYSCLK_P]
# create_clock -period 5.000 -name SYSCLK_N -waveform {0.000 2.500} [get_ports SYSCLK_N]


###### LED Pin assignment works ########
set_property PACKAGE_PIN AM39 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN AN39 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN AR37 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN AT37 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN AR35 [get_ports {GPIO_LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[4]}]
set_property PACKAGE_PIN AP41 [get_ports {GPIO_LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[5]}]
set_property PACKAGE_PIN AP42 [get_ports {GPIO_LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[6]}]
set_property PACKAGE_PIN AU39 [get_ports {GPIO_LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[7]}]


###### reset button Pin assignment  --> SW5 ########
# set_property PACKAGE_PIN AP40 [get_ports reset]
# set_property IOSTANDARD LVCMOS18 [get_ports reset]


###### Up-Down Dip Switch Pin assignment ########
# set_property PACKAGE_PIN AV30 [get_ports DIP_SW0]
# set_property IOSTANDARD LVCMOS18 [get_ports DIP_SW0]
# set_property PACKAGE_PIN AY33 [get_ports DIP_SW1]
# set_property IOSTANDARD LVCMOS18 [get_ports DIP_SW1]
# set_property PACKAGE_PIN BA31 [get_ports DIP_SW2]
# set_property IOSTANDARD LVCMOS18 [get_ports DIP_SW2]


###### XADC GPIOs Pin assignment ########
#  AN41, AN40, AR39, and AR38  #
#  19  , 20  , 17    and 18    #
# set_property PACKAGE_PIN AN41 [get_ports GPIO_19]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_19]

# set_property PACKAGE_PIN AN40 [get_ports GPIO_20]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_20]

# set_property PACKAGE_PIN AR39 [get_ports GPIO_17]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_17]

# set_property PACKAGE_PIN AR38 [get_ports GPIO_18]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_18]



###### FMC1 HPC Pin assignment ########
###### Generate a LVDS Differential Signal as 10Hz ########

set_property PACKAGE_PIN E35 [get_ports DACData6_N[2]] 
set_property PACKAGE_PIN E34 [get_ports DACData6_P[2]] 
set_property PACKAGE_PIN D36 [get_ports DACData6_N[0]] 
set_property PACKAGE_PIN D35 [get_ports DACData6_P[0]] 
set_property PACKAGE_PIN D33 [get_ports DACData6_N[5]] 
set_property PACKAGE_PIN E33 [get_ports DACData6_P[5]] 
set_property PACKAGE_PIN G33 [get_ports DATACLK_N[5]]  
set_property PACKAGE_PIN H33 [get_ports DATACLK_P[5]]  
set_property PACKAGE_PIN F35 [get_ports DACCLK_N[4]]   
set_property PACKAGE_PIN F34 [get_ports DACCLK_P[4]]   
set_property PACKAGE_PIN F32 [get_ports DACData6_N[1]] 
set_property PACKAGE_PIN G32 [get_ports DACData6_P[1]] 
set_property PACKAGE_PIN G37 [get_ports DACData6_N[8]] 
set_property PACKAGE_PIN G36 [get_ports DACData6_P[8]] 
set_property PACKAGE_PIN C39 [get_ports DACData6_N[7]] 
set_property PACKAGE_PIN C38 [get_ports DACData6_P[7]] 
set_property PACKAGE_PIN H36 [get_ports DAC_CSB[2]]    
set_property PACKAGE_PIN J36 [get_ports PLL_CSB[2]]    
set_property PACKAGE_PIN D32 [get_ports DACData5_N[10]]
set_property PACKAGE_PIN E32 [get_ports DACData5_P[10]]
set_property PACKAGE_PIN G38 [get_ports DACData6_N[11]]
set_property PACKAGE_PIN H38 [get_ports DACData6_P[11]]
set_property PACKAGE_PIN J38 [get_ports DACCLK_N[5]]   
set_property PACKAGE_PIN J37 [get_ports DACCLK_P[5]]   
set_property PACKAGE_PIN B38 [get_ports DAC_CSB[4]]    
set_property PACKAGE_PIN B37 [get_ports PLL_CSB[4]]    
set_property PACKAGE_PIN A37 [get_ports DACData5_N[7]] 
set_property PACKAGE_PIN B36 [get_ports DACData5_P[7]] 
set_property PACKAGE_PIN E38 [get_ports DACData7_N[1]] 
set_property PACKAGE_PIN E37 [get_ports DACData7_P[1]] 
set_property PACKAGE_PIN C34 [get_ports PLL_CSB[3]]    
set_property PACKAGE_PIN C33 [get_ports DAC_CSB[3]]    
set_property PACKAGE_PIN A39 [get_ports DACData5_N[4]] 
set_property PACKAGE_PIN B39 [get_ports DACData5_P[4]] 
set_property PACKAGE_PIN C36 [get_ports DACData7_N[0]] 
set_property PACKAGE_PIN C35 [get_ports DACData7_P[0]] 
# set_property PACKAGE_PIN E39 [get_ports Free_HA18_N] 
# set_property PACKAGE_PIN F39 [get_ports Free_HA18_P] 
set_property PACKAGE_PIN B33 [get_ports PLL_CSB[1]]    
set_property PACKAGE_PIN B32 [get_ports DAC_CSB[1]]    
# set_property PACKAGE_PIN A34 [get_ports Free_HA20_N] 
# set_property PACKAGE_PIN B34 [get_ports Free_HA20_P] 
set_property PACKAGE_PIN D38 [get_ports SYNC_N]        
set_property PACKAGE_PIN D37 [get_ports SYNC_P]        
set_property PACKAGE_PIN F37 [get_ports DATACLK_N[6]]  
set_property PACKAGE_PIN F36 [get_ports DATACLK_P[6]]  
set_property PACKAGE_PIN A36 [get_ports DACData7_N[4]] 
set_property PACKAGE_PIN A35 [get_ports DACData7_P[4]] 
# set_property PACKAGE_PIN J26 [get_ports FMC1_HPC_HB00_CC_N]      # [FMC1_HPC_HB00_CC_N]      NC: Faulty on the VC707    
# set_property PACKAGE_PIN J25 [get_ports FMC1_HPC_HB00_CC_P]      # [FMC1_HPC_HB00_CC_P]      NC: Faulty on the VC707 
set_property PACKAGE_PIN H29 [get_ports DACData7_N[5]] 
set_property PACKAGE_PIN H28 [get_ports DACData7_P[5]] 
set_property PACKAGE_PIN J28 [get_ports DAC_CSB[0]]    
set_property PACKAGE_PIN K28 [get_ports PLL_CSB[0]]    
set_property PACKAGE_PIN G29 [get_ports DACData8_N[7]] 
set_property PACKAGE_PIN G28 [get_ports DACData8_P[7]] 
set_property PACKAGE_PIN G24 [get_ports PLL_CSB[5]]    
set_property PACKAGE_PIN H24 [get_ports DAC_CSB[7]]    
set_property PACKAGE_PIN J27 [get_ports DAC_SCLK]      
set_property PACKAGE_PIN K27 [get_ports DAC_MOSI]      
set_property PACKAGE_PIN J23 [get_ports DACData7_N[8]] 
set_property PACKAGE_PIN K23 [get_ports DACData7_P[8]] 
set_property PACKAGE_PIN G27 [get_ports DACData7_N[9]] 
set_property PACKAGE_PIN G26 [get_ports DACData7_P[9]] 
set_property PACKAGE_PIN H26 [get_ports DAC_CSB[5]]    
set_property PACKAGE_PIN H25 [get_ports RESETB]        
set_property PACKAGE_PIN G23 [get_ports PLL_MISO]      
set_property PACKAGE_PIN H23 [get_ports PLL_SCK]       
set_property PACKAGE_PIN L22 [get_ports DACData7_N[10]]
set_property PACKAGE_PIN M22 [get_ports DACData7_P[10]]
set_property PACKAGE_PIN J22 [get_ports DACData7_N[11]]
set_property PACKAGE_PIN K22 [get_ports DACData7_P[11]]
set_property PACKAGE_PIN K25 [get_ports PLL_CSB[7]]    
set_property PACKAGE_PIN K24 [get_ports PLL_CSB[6]]    
set_property PACKAGE_PIN P26 [get_ports DAC_CSB[6]]    
set_property PACKAGE_PIN P25 [get_ports PLL_MOSI]      
set_property PACKAGE_PIN H21 [get_ports DACCLK_N[6]]   
set_property PACKAGE_PIN J21 [get_ports DACCLK_P[6]]   
set_property PACKAGE_PIN L21 [get_ports DACData8_N[0]] 
set_property PACKAGE_PIN M21 [get_ports DACData8_P[0]] 
set_property PACKAGE_PIN N26 [get_ports DACData8_N[4]] 
set_property PACKAGE_PIN N25 [get_ports DACData8_P[4]] 
set_property PACKAGE_PIN L24 [get_ports DACData8_N[1]] 
set_property PACKAGE_PIN M24 [get_ports DACData8_P[1]] 
set_property PACKAGE_PIN G22 [get_ports DACData8_N[2]] 
set_property PACKAGE_PIN G21 [get_ports DACData8_P[2]] 
# set_property PACKAGE_PIN L26 [get_ports FMC1_HPC_HB19_N]         # [FMC1_HPC_HB19_N]         NC      
set_property PACKAGE_PIN L25 [get_ports PLL_SYNC]      
set_property PACKAGE_PIN N21 [get_ports DACData8_N[3]] 
set_property PACKAGE_PIN P21 [get_ports DACData8_P[3]] 
# set_property PACKAGE_PIN P23 [get_ports Free_HB21_N]    
# set_property PACKAGE_PIN P22 [get_ports Free_HB21_P]    
set_property PACKAGE_PIN K40 [get_ports DACData6_N[4]] 
set_property PACKAGE_PIN K39 [get_ports DACData6_P[4]] 
set_property PACKAGE_PIN J41 [get_ports DACData5_N[11]]
set_property PACKAGE_PIN J40 [get_ports DACData5_P[11]]
set_property PACKAGE_PIN N41 [get_ports DACData6_N[3]] 
set_property PACKAGE_PIN P41 [get_ports DACData6_P[3]] 
set_property PACKAGE_PIN L42 [get_ports DACData6_N[6]] 
set_property PACKAGE_PIN M42 [get_ports DACData6_P[6]] 
set_property PACKAGE_PIN H41 [get_ports DACData6_N[9]] 
set_property PACKAGE_PIN H40 [get_ports DACData6_P[9]] 
set_property PACKAGE_PIN L41 [get_ports DACData5_N[8]] 
set_property PACKAGE_PIN M41 [get_ports DACData5_P[8]] 
set_property PACKAGE_PIN J42 [get_ports DACData5_N[9]] 
set_property PACKAGE_PIN K42 [get_ports DACData5_P[9]] 
set_property PACKAGE_PIN G42 [get_ports DACData5_N[6]] 
set_property PACKAGE_PIN G41 [get_ports DACData5_P[6]] 
set_property PACKAGE_PIN M38 [get_ports DACData6_N[10]]
set_property PACKAGE_PIN M37 [get_ports DACData6_P[10]]
set_property PACKAGE_PIN P42 [get_ports DACData5_N[5]] 
set_property PACKAGE_PIN R42 [get_ports DACData5_P[5]] 
set_property PACKAGE_PIN M39 [get_ports DATACLK_N[4]]  
set_property PACKAGE_PIN N38 [get_ports DATACLK_P[4]]  
set_property PACKAGE_PIN F41 [get_ports DACData5_N[2]] 
set_property PACKAGE_PIN F40 [get_ports DACData5_P[2]] 
set_property PACKAGE_PIN P40 [get_ports DACData5_N[3]] 
set_property PACKAGE_PIN R40 [get_ports DACData5_P[3]] 
set_property PACKAGE_PIN G39 [get_ports DACData5_N[1]] 
set_property PACKAGE_PIN H39 [get_ports DACData5_P[1]] 
set_property PACKAGE_PIN N40 [get_ports DACData5_N[0]] 
set_property PACKAGE_PIN N39 [get_ports DACData5_P[0]] 
set_property PACKAGE_PIN L37 [get_ports DACData7_N[2]] 
set_property PACKAGE_PIN M36 [get_ports DACData7_P[2]] 
set_property PACKAGE_PIN K38 [get_ports DACData7_N[3]] 
set_property PACKAGE_PIN K37 [get_ports DACData7_P[3]] 
set_property PACKAGE_PIN K32 [get_ports DACCLK_N[7]]   
set_property PACKAGE_PIN L31 [get_ports DACCLK_P[7]]   
set_property PACKAGE_PIN L32 [get_ports DACData8_N[11]]
set_property PACKAGE_PIN M32 [get_ports DACData8_P[11]]
# set_property PACKAGE_PIN W31 [get_ports FMC1_HPC_LA19_N]         # [FMC1_HPC_LA19_N]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN W30 [get_ports FMC1_HPC_LA19_P]         # [FMC1_HPC_LA19_P]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN Y30 [get_ports FMC1_HPC_LA20_N]         # [FMC1_HPC_LA20_N]      NC: Faulty on the VC707      
# set_property PACKAGE_PIN Y29 [get_ports FMC1_HPC_LA20_P]         # [FMC1_HPC_LA20_P]      NC: Faulty on the VC707      
set_property PACKAGE_PIN N29 [get_ports DACData7_N[6]] 
set_property PACKAGE_PIN N28 [get_ports DACData7_P[6]] 
set_property PACKAGE_PIN P28 [get_ports DACData7_N[7]] 
set_property PACKAGE_PIN R28 [get_ports DACData7_P[7]] 
set_property PACKAGE_PIN N31 [get_ports DACData8_N[10]]
set_property PACKAGE_PIN P30 [get_ports DACData8_P[10]]
# set_property PACKAGE_PIN P31 [get_ports FMC1_HPC_LA24_N]         # [FMC1_HPC_LA24_N]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN R30 [get_ports FMC1_HPC_LA24_P]         # [FMC1_HPC_LA24_P]      NC: Faulty on the VC707       
set_property PACKAGE_PIN K30 [get_ports DACData8_N[6]]
set_property PACKAGE_PIN K29 [get_ports DACData8_P[6]]
set_property PACKAGE_PIN H30 [get_ports DACData8_N[8]]
set_property PACKAGE_PIN J30 [get_ports DACData8_P[8]]
set_property PACKAGE_PIN H31 [get_ports DACData8_N[9]]
set_property PACKAGE_PIN J31 [get_ports DACData8_P[9]]
set_property PACKAGE_PIN L30 [get_ports DACData8_N[5]]
set_property PACKAGE_PIN L29 [get_ports DACData8_P[5]]
# set_property PACKAGE_PIN T30 [get_ports FMC1_HPC_LA29_N]         # [FMC1_HPC_LA29_N]      NC: Faulty on the VC707
# set_property PACKAGE_PIN T29 [get_ports FMC1_HPC_LA29_P]         # [FMC1_HPC_LA29_P]      NC: Faulty on the VC707
# set_property PACKAGE_PIN V31 [get_ports FMC1_HPC_LA30_N]         # [FMC1_HPC_LA30_N]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN V30 [get_ports FMC1_HPC_LA30_P]         # [FMC1_HPC_LA30_P]      NC: Faulty on the VC707       
set_property PACKAGE_PIN M29 [get_ports DATACLK_N[7]]     
set_property PACKAGE_PIN M28 [get_ports DATACLK_P[7]]     
# set_property PACKAGE_PIN U29 [get_ports FMC1_HPC_LA32_N]         # [FMC1_HPC_LA32_N]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN V29 [get_ports FMC1_HPC_LA32_P]         # [FMC1_HPC_LA32_P]      NC: Faulty on the VC707       
# set_property PACKAGE_PIN T31 [get_ports FMC1_HPC_LA33_N]         # [FMC1_HPC_LA33_N]      NC: Faulty on the VC707
# set_property PACKAGE_PIN U31 [get_ports FMC1_HPC_LA33_P]         # [FMC1_HPC_LA33_P]      NC: Faulty on the VC707



set_property IOSTANDARD LVDS [get_ports DACData6_N[2]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[2]] 
set_property IOSTANDARD LVDS [get_ports DACData6_N[0]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[0]] 
set_property IOSTANDARD LVDS [get_ports DACData6_N[5]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[5]] 
set_property IOSTANDARD LVDS [get_ports DATACLK_N[5]]  
set_property IOSTANDARD LVDS [get_ports DATACLK_P[5]]  
set_property IOSTANDARD LVDS [get_ports DACCLK_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACCLK_P[4]]   
set_property IOSTANDARD LVDS [get_ports DACData6_N[1]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[1]] 
set_property IOSTANDARD LVDS [get_ports DACData6_N[8]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[8]] 
set_property IOSTANDARD LVDS [get_ports DACData6_N[7]] 
set_property IOSTANDARD LVDS [get_ports DACData6_P[7]] 
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[2]]
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[2]]
set_property IOSTANDARD LVDS [get_ports DACData5_N[10]]
set_property IOSTANDARD LVDS [get_ports DACData5_P[10]]
set_property IOSTANDARD LVDS [get_ports DACData6_N[11]]
set_property IOSTANDARD LVDS [get_ports DACData6_P[11]]
set_property IOSTANDARD LVDS [get_ports DACCLK_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACCLK_P[5]]   
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[4]]
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[4]]
set_property IOSTANDARD LVDS [get_ports DACData5_N[7]] 
set_property IOSTANDARD LVDS [get_ports DACData5_P[7]] 
set_property IOSTANDARD LVDS [get_ports DACData7_N[1]] 
set_property IOSTANDARD LVDS [get_ports DACData7_P[1]] 
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[3]]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[3]]
set_property IOSTANDARD LVDS [get_ports DACData5_N[4]] 
set_property IOSTANDARD LVDS [get_ports DACData5_P[4]] 
set_property IOSTANDARD LVDS [get_ports DACData7_N[0]] 
set_property IOSTANDARD LVDS [get_ports DACData7_P[0]] 
# set_property IOSTANDARD LVDS [get_ports Free_HA18_N]        # [FMC1_HPC_HA18_N]             Free_HA18_N       
# set_property IOSTANDARD LVDS [get_ports Free_HA18_P]        # [FMC1_HPC_HA18_P]             Free_HA18_P       
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[1]]       
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[1]]       
# set_property IOSTANDARD LVDS [get_ports Free_HA20_N]        # [FMC1_HPC_HA20_N]             Free_HA20_N       
# set_property IOSTANDARD LVDS [get_ports Free_HA20_P]        # [FMC1_HPC_HA20_P]             Free_HA20_P       
set_property IOSTANDARD LVDS [get_ports SYNC_N]        
set_property IOSTANDARD LVDS [get_ports SYNC_P]        
set_property IOSTANDARD LVDS [get_ports DATACLK_N[6]]    
set_property IOSTANDARD LVDS [get_ports DATACLK_P[6]]    
set_property IOSTANDARD LVDS [get_ports DACData7_N[4]]    
set_property IOSTANDARD LVDS [get_ports DACData7_P[4]]    
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_HB00_CC_N]     # [FMC1_HPC_HB00_CC_N]      NC: Faulty on the VC707     
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_HB00_CC_P]     # [FMC1_HPC_HB00_CC_P]      NC: Faulty on the VC707     
set_property IOSTANDARD LVDS [get_ports DACData7_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACData7_P[5]]   
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[0]]  
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[0]]  
set_property IOSTANDARD LVDS [get_ports DACData8_N[7]]   
set_property IOSTANDARD LVDS [get_ports DACData8_P[7]]   
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[5]]  
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[7]]  
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SCLK]    
set_property IOSTANDARD LVCMOS18 [get_ports DAC_MOSI]    
set_property IOSTANDARD LVDS [get_ports DACData7_N[8]]   
set_property IOSTANDARD LVDS [get_ports DACData7_P[8]]   
set_property IOSTANDARD LVDS [get_ports DACData7_N[9]]   
set_property IOSTANDARD LVDS [get_ports DACData7_P[9]]   
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[5]]  
set_property IOSTANDARD LVCMOS18 [get_ports RESETB]      
set_property IOSTANDARD LVCMOS18 [get_ports PLL_MISO]    
set_property IOSTANDARD LVCMOS18 [get_ports PLL_SCK]     
set_property IOSTANDARD LVDS [get_ports DACData7_N[10]]  
set_property IOSTANDARD LVDS [get_ports DACData7_P[10]]  
set_property IOSTANDARD LVDS [get_ports DACData7_N[11]]  
set_property IOSTANDARD LVDS [get_ports DACData7_P[11]]  
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[7]]  
set_property IOSTANDARD LVCMOS18 [get_ports PLL_CSB[6]]  
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CSB[6]]  
set_property IOSTANDARD LVCMOS18 [get_ports PLL_MOSI]    
set_property IOSTANDARD LVDS [get_ports DACCLK_N[6]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[6]]     
set_property IOSTANDARD LVDS [get_ports DACData8_N[0]]   
set_property IOSTANDARD LVDS [get_ports DACData8_P[0]]   
set_property IOSTANDARD LVDS [get_ports DACData8_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACData8_P[4]]   
set_property IOSTANDARD LVDS [get_ports DACData8_N[1]]   
set_property IOSTANDARD LVDS [get_ports DACData8_P[1]]   
set_property IOSTANDARD LVDS [get_ports DACData8_N[2]]   
set_property IOSTANDARD LVDS [get_ports DACData8_P[2]]   
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_HB19_N]        # [FMC1_HPC_HB19_N]         NC       
set_property IOSTANDARD LVCMOS18 [get_ports PLL_SYNC]      
set_property IOSTANDARD LVDS [get_ports DACData8_N[3]]      
set_property IOSTANDARD LVDS [get_ports DACData8_P[3]]      
# set_property IOSTANDARD LVDS [get_ports Free_HB21_N]        # [FMC1_HPC_HB21_N]             Free_HB21_N       
# set_property IOSTANDARD LVDS [get_ports Free_HB21_P]        # [FMC1_HPC_HB21_P]             Free_HB21_P       
set_property IOSTANDARD LVDS [get_ports DACData6_N[4]]     
set_property IOSTANDARD LVDS [get_ports DACData6_P[4]]     
set_property IOSTANDARD LVDS [get_ports DACData5_N[11]]    
set_property IOSTANDARD LVDS [get_ports DACData5_P[11]]    
set_property IOSTANDARD LVDS [get_ports DACData6_N[3]]       
set_property IOSTANDARD LVDS [get_ports DACData6_P[3]]       
set_property IOSTANDARD LVDS [get_ports DACData6_N[6]]       
set_property IOSTANDARD LVDS [get_ports DACData6_P[6]]       
set_property IOSTANDARD LVDS [get_ports DACData6_N[9]]       
set_property IOSTANDARD LVDS [get_ports DACData6_P[9]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[8]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[8]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[9]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[9]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[6]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[6]]       
set_property IOSTANDARD LVDS [get_ports DACData6_N[10]]       
set_property IOSTANDARD LVDS [get_ports DACData6_P[10]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[5]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[5]]       
set_property IOSTANDARD LVDS [get_ports DATACLK_N[4]]       
set_property IOSTANDARD LVDS [get_ports DATACLK_P[4]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[2]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[2]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[3]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[3]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[1]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[1]]       
set_property IOSTANDARD LVDS [get_ports DACData5_N[0]]       
set_property IOSTANDARD LVDS [get_ports DACData5_P[0]]       
set_property IOSTANDARD LVDS [get_ports DACData7_N[2]]       
set_property IOSTANDARD LVDS [get_ports DACData7_P[2]]       
set_property IOSTANDARD LVDS [get_ports DACData7_N[3]]       
set_property IOSTANDARD LVDS [get_ports DACData7_P[3]]       
set_property IOSTANDARD LVDS [get_ports DACCLK_N[7]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[7]]     
set_property IOSTANDARD LVDS [get_ports DACData8_N[11]]    
set_property IOSTANDARD LVDS [get_ports DACData8_P[11]]    
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA19_N]        # [FMC1_HPC_LA19_N]      NC: Faulty on the VC707        
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA19_P]        # [FMC1_HPC_LA19_P]      NC: Faulty on the VC707        
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA20_N]        # [FMC1_HPC_LA20_N]      NC: Faulty on the VC707       
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA20_P]        # [FMC1_HPC_LA20_P]      NC: Faulty on the VC707       
set_property IOSTANDARD LVDS [get_ports DACData7_N[6]]        
set_property IOSTANDARD LVDS [get_ports DACData7_P[6]]        
set_property IOSTANDARD LVDS [get_ports DACData7_N[7]]        
set_property IOSTANDARD LVDS [get_ports DACData7_P[7]]        
set_property IOSTANDARD LVDS [get_ports DACData8_N[10]]        
set_property IOSTANDARD LVDS [get_ports DACData8_P[10]]        
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA24_N]        # [FMC1_HPC_LA24_N]      NC: Faulty on the VC707       
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA24_P]        # [FMC1_HPC_LA24_P]      NC: Faulty on the VC707       
set_property IOSTANDARD LVDS [get_ports DACData8_N[6]]           
set_property IOSTANDARD LVDS [get_ports DACData8_P[6]]           
set_property IOSTANDARD LVDS [get_ports DACData8_N[8]]           
set_property IOSTANDARD LVDS [get_ports DACData8_P[8]]           
set_property IOSTANDARD LVDS [get_ports DACData8_N[9]]           
set_property IOSTANDARD LVDS [get_ports DACData8_P[9]]           
set_property IOSTANDARD LVDS [get_ports DACData8_N[5]]           
set_property IOSTANDARD LVDS [get_ports DACData8_P[5]]           
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA29_N]        # [FMC1_HPC_LA29_N]      NC: Faulty on the VC707                
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA29_P]        # [FMC1_HPC_LA29_P]      NC: Faulty on the VC707                
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA30_N]        # [FMC1_HPC_LA30_N]      NC: Faulty on the VC707                                              
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA30_P]        # [FMC1_HPC_LA30_P]      NC: Faulty on the VC707                                              
set_property IOSTANDARD LVDS [get_ports DATACLK_N[7]]                                                  
set_property IOSTANDARD LVDS [get_ports DATACLK_P[7]]                                                  
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA32_N]        # [FMC1_HPC_LA32_N]      NC: Faulty on the VC707                                              
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA32_P]        # [FMC1_HPC_LA32_P]      NC: Faulty on the VC707                                              
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA33_N]        # [FMC1_HPC_LA33_N]      NC: Faulty on the VC707                
# set_property IOSTANDARD LVDS [get_ports FMC1_HPC_LA33_P]        # [FMC1_HPC_LA33_P]      NC: Faulty on the VC707                
                  


###### FMC2 HPC Pin assignment (no HB!) ########
###### Generate a LVDS Differential Signal as 10Hz ########


set_property PACKAGE_PIN AC33 [get_ports DACData2_N[9]] 
set_property PACKAGE_PIN AB33 [get_ports DACData2_P[9]] 
set_property PACKAGE_PIN AD33 [get_ports DACData2_N[5]] 
set_property PACKAGE_PIN AD32 [get_ports DACData2_P[5]] 
set_property PACKAGE_PIN AD30 [get_ports DACData3_N[0]] 
set_property PACKAGE_PIN AC30 [get_ports DACData3_P[0]] 
set_property PACKAGE_PIN AA30 [get_ports DACCLK_N[1]]   
set_property PACKAGE_PIN AA29 [get_ports DACCLK_P[1]]   
set_property PACKAGE_PIN AC29 [get_ports DACData2_N[6]] 
set_property PACKAGE_PIN AB29 [get_ports DACData2_P[6]] 
set_property PACKAGE_PIN Y33  [get_ports DACData2_N[7]] 
set_property PACKAGE_PIN Y32  [get_ports DACData2_P[7]] 
set_property PACKAGE_PIN AB32 [get_ports ALARM]       
set_property PACKAGE_PIN AB31 [get_ports DAC_MISO]      
set_property PACKAGE_PIN AD31 [get_ports DACData3_N[3]] 
set_property PACKAGE_PIN AC31 [get_ports DACData3_P[3]] 
set_property PACKAGE_PIN AA32 [get_ports DACData2_N[3]] 
set_property PACKAGE_PIN AA31 [get_ports DACData2_P[3]] 
set_property PACKAGE_PIN AE30 [get_ports DACData2_N[4]] 
set_property PACKAGE_PIN AE29 [get_ports DACData2_P[4]] 
set_property PACKAGE_PIN AF32 [get_ports SLEEP]     
set_property PACKAGE_PIN AF31 [get_ports TXENABLE]           
set_property PACKAGE_PIN AE35 [get_ports DACData3_N[5]]       
set_property PACKAGE_PIN AE34 [get_ports DACData3_P[5]] 
set_property PACKAGE_PIN AG34 [get_ports DACData2_N[8]] 
set_property PACKAGE_PIN AF34 [get_ports DACData2_P[8]] 
set_property PACKAGE_PIN AE33 [get_ports DACCLK_N[0]]   
set_property PACKAGE_PIN AE32 [get_ports DACCLK_P[0]]   
set_property PACKAGE_PIN AF36 [get_ports DACData3_N[7]] 
set_property PACKAGE_PIN AF35 [get_ports DACData3_P[7]] 
set_property PACKAGE_PIN AF37 [get_ports DACData2_N[2]] 
set_property PACKAGE_PIN AE37 [get_ports DACData2_P[2]] 
set_property PACKAGE_PIN AH36 [get_ports DACData1_N[7]] 
set_property PACKAGE_PIN AG36 [get_ports DACData1_P[7]] 
set_property PACKAGE_PIN AD35 [get_ports DACData3_N[8]] 
set_property PACKAGE_PIN AC34 [get_ports DACData3_P[8]] 
set_property PACKAGE_PIN AB37 [get_ports DACData3_N[11]]
set_property PACKAGE_PIN AB36 [get_ports DACData3_P[11]]
set_property PACKAGE_PIN AC36 [get_ports DACData1_N[6]] 
set_property PACKAGE_PIN AC35 [get_ports DACData1_P[6]] 
set_property PACKAGE_PIN AD37 [get_ports DACData1_N[3]] 
set_property PACKAGE_PIN AD36 [get_ports DACData1_P[3]] 
set_property PACKAGE_PIN AA35 [get_ports DACCLK_N[2]]   
set_property PACKAGE_PIN AA34 [get_ports DACCLK_P[2]]   
set_property PACKAGE_PIN AA36 [get_ports DACData4_N[0]] 
set_property PACKAGE_PIN Y35  [get_ports DACData4_P[0]] 
set_property PACKAGE_PIN AA37 [get_ports DACData4_N[2]] 
set_property PACKAGE_PIN Y37  [get_ports DACData4_P[2]] 
set_property PACKAGE_PIN AD41 [get_ports DACData2_N[11]]
set_property PACKAGE_PIN AD40 [get_ports DACData2_P[11]]
set_property PACKAGE_PIN AG41 [get_ports DATACLK_N[1]]  
set_property PACKAGE_PIN AF41 [get_ports DATACLK_P[1]]  
set_property PACKAGE_PIN AL39 [get_ports DACData2_N[10]]
set_property PACKAGE_PIN AK39 [get_ports DACData2_P[10]]
set_property PACKAGE_PIN AK42 [get_ports DACData3_N[2]] 
set_property PACKAGE_PIN AJ42 [get_ports DACData3_P[2]] 
set_property PACKAGE_PIN AL42 [get_ports DACData3_N[1]] 
set_property PACKAGE_PIN AL41 [get_ports DACData3_P[1]] 
set_property PACKAGE_PIN AG42 [get_ports DACData2_N[0]] 
set_property PACKAGE_PIN AF42 [get_ports DACData2_P[0]] 
set_property PACKAGE_PIN AE38 [get_ports DACData2_N[1]] 
set_property PACKAGE_PIN AD38 [get_ports DACData2_P[1]] 
set_property PACKAGE_PIN AC41 [get_ports DATACLK_N[2]]  
set_property PACKAGE_PIN AC40 [get_ports DATACLK_P[2]]  
set_property PACKAGE_PIN AE42 [get_ports DACData3_N[4]] 
set_property PACKAGE_PIN AD42 [get_ports DACData3_P[4]] 
set_property PACKAGE_PIN AK38 [get_ports DACData1_N[11]]
set_property PACKAGE_PIN AJ38 [get_ports DACData1_P[11]]
set_property PACKAGE_PIN AB42 [get_ports DACData1_N[4]] 
set_property PACKAGE_PIN AB41 [get_ports DACData1_P[4]] 
set_property PACKAGE_PIN AA42 [get_ports DACData3_N[9]] 
set_property PACKAGE_PIN Y42  [get_ports DACData3_P[9]] 
set_property PACKAGE_PIN AA39 [get_ports DACData3_N[6]] 
set_property PACKAGE_PIN Y39  [get_ports DACData3_P[6]] 
set_property PACKAGE_PIN Y40  [get_ports DACData1_N[10]]
set_property PACKAGE_PIN W40  [get_ports DACData1_P[10]]
set_property PACKAGE_PIN AB39 [get_ports DACData1_N[2]] 
set_property PACKAGE_PIN AB38 [get_ports DACData1_P[2]] 
set_property PACKAGE_PIN AC39 [get_ports DACData4_N[3]] 
set_property PACKAGE_PIN AC38 [get_ports DACData4_P[3]] 
set_property PACKAGE_PIN AJ41 [get_ports DACData3_N[10]]
set_property PACKAGE_PIN AJ40 [get_ports DACData3_P[10]]
set_property PACKAGE_PIN U38  [get_ports DACData1_N[5]] 
set_property PACKAGE_PIN U37  [get_ports DACData1_P[5]] 
set_property PACKAGE_PIN T37  [get_ports DACData1_N[1]] 
set_property PACKAGE_PIN U36  [get_ports DACData1_P[1]] 
set_property PACKAGE_PIN U33  [get_ports DACData4_N[1]] 
set_property PACKAGE_PIN U32  [get_ports DACData4_P[1]] 
set_property PACKAGE_PIN V34  [get_ports DACData1_N[9]] 
set_property PACKAGE_PIN V33  [get_ports DACData1_P[9]] 
set_property PACKAGE_PIN P36  [get_ports DATACLK_N[3]]  
set_property PACKAGE_PIN P35  [get_ports DATACLK_P[3]]  
set_property PACKAGE_PIN W33  [get_ports DACData4_N[4]] 
set_property PACKAGE_PIN W32  [get_ports DACData4_P[4]] 
set_property PACKAGE_PIN R39  [get_ports DACData1_N[8]] 
set_property PACKAGE_PIN R38  [get_ports DACData1_P[8]] 
set_property PACKAGE_PIN T35  [get_ports DACData4_N[5]] 
set_property PACKAGE_PIN U34  [get_ports DACData4_P[5]] 
set_property PACKAGE_PIN R34  [get_ports DACData4_N[6]] 
set_property PACKAGE_PIN R33  [get_ports DACData4_P[6]] 
set_property PACKAGE_PIN N34  [get_ports DATACLK_N[0]]  
set_property PACKAGE_PIN N33  [get_ports DATACLK_P[0]]  
set_property PACKAGE_PIN P33  [get_ports DACData1_N[0]] 
set_property PACKAGE_PIN P32  [get_ports DACData1_P[0]] 
set_property PACKAGE_PIN V36  [get_ports DACData4_N[7]] 
set_property PACKAGE_PIN V35  [get_ports DACData4_P[7]] 
set_property PACKAGE_PIN W37  [get_ports DACData4_N[8]] 
set_property PACKAGE_PIN W36  [get_ports DACData4_P[8]] 
set_property PACKAGE_PIN R32  [get_ports DACData4_N[9]] 
set_property PACKAGE_PIN T32  [get_ports DACData4_P[9]] 
set_property PACKAGE_PIN V40  [get_ports DACData4_N[10]]
set_property PACKAGE_PIN V39  [get_ports DACData4_P[10]]
set_property PACKAGE_PIN P38  [get_ports DACData4_N[11]]
set_property PACKAGE_PIN P37  [get_ports DACData4_P[11]]
set_property PACKAGE_PIN R37  [get_ports DACCLK_N[3]]   
set_property PACKAGE_PIN T36  [get_ports DACCLK_P[3]]   
                                                                                
                                                                                
                                                                                
set_property IOSTANDARD LVDS [get_ports DACData2_N[9]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[9]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[5]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[0]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[0]]   
set_property IOSTANDARD LVDS [get_ports DACCLK_N[1]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[1]]     
set_property IOSTANDARD LVDS [get_ports DACData2_N[6]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[6]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[7]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[7]]   
set_property IOSTANDARD LVCMOS18 [get_ports ALARM]       
set_property IOSTANDARD LVCMOS18 [get_ports DAC_MISO]    
set_property IOSTANDARD LVDS [get_ports DACData3_N[3]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[3]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[3]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[3]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[4]]   
set_property IOSTANDARD LVCMOS18 [get_ports SLEEP]       
set_property IOSTANDARD LVCMOS18 [get_ports TXENABLE]      
set_property IOSTANDARD LVDS [get_ports DACData3_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[5]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[8]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[8]]   
set_property IOSTANDARD LVDS [get_ports DACCLK_N[0]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[0]]     
set_property IOSTANDARD LVDS [get_ports DACData3_N[7]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[7]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[2]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[2]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[7]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[7]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[8]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[8]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[11]]  
set_property IOSTANDARD LVDS [get_ports DACData3_P[11]]  
set_property IOSTANDARD LVDS [get_ports DACData1_N[6]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[6]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[3]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[3]]   
set_property IOSTANDARD LVDS [get_ports DACCLK_N[2]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[2]]     
set_property IOSTANDARD LVDS [get_ports DACData4_N[0]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[0]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[2]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[2]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[11]]  
set_property IOSTANDARD LVDS [get_ports DACData2_P[11]]  
set_property IOSTANDARD LVDS [get_ports DATACLK_N[1]]    
set_property IOSTANDARD LVDS [get_ports DATACLK_P[1]]    
set_property IOSTANDARD LVDS [get_ports DACData2_N[10]]  
set_property IOSTANDARD LVDS [get_ports DACData2_P[10]]  
set_property IOSTANDARD LVDS [get_ports DACData3_N[2]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[2]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[1]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[1]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[0]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[0]]   
set_property IOSTANDARD LVDS [get_ports DACData2_N[1]]   
set_property IOSTANDARD LVDS [get_ports DACData2_P[1]]   
set_property IOSTANDARD LVDS [get_ports DATACLK_N[2]]    
set_property IOSTANDARD LVDS [get_ports DATACLK_P[2]]    
set_property IOSTANDARD LVDS [get_ports DACData3_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[4]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[11]]  
set_property IOSTANDARD LVDS [get_ports DACData1_P[11]]  
set_property IOSTANDARD LVDS [get_ports DACData1_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[4]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[9]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[9]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[6]]   
set_property IOSTANDARD LVDS [get_ports DACData3_P[6]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[10]]  
set_property IOSTANDARD LVDS [get_ports DACData1_P[10]]  
set_property IOSTANDARD LVDS [get_ports DACData1_N[2]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[2]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[3]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[3]]   
set_property IOSTANDARD LVDS [get_ports DACData3_N[10]]  
set_property IOSTANDARD LVDS [get_ports DACData3_P[10]]  
set_property IOSTANDARD LVDS [get_ports DACData1_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[5]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[1]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[1]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[1]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[1]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[9]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[9]]   
set_property IOSTANDARD LVDS [get_ports DATACLK_N[3]]    
set_property IOSTANDARD LVDS [get_ports DATACLK_P[3]]    
set_property IOSTANDARD LVDS [get_ports DACData4_N[4]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[4]]   
set_property IOSTANDARD LVDS [get_ports DACData1_N[8]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[8]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[5]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[5]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[6]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[6]]   
set_property IOSTANDARD LVDS [get_ports DATACLK_N[0]]    
set_property IOSTANDARD LVDS [get_ports DATACLK_P[0]]    
set_property IOSTANDARD LVDS [get_ports DACData1_N[0]]   
set_property IOSTANDARD LVDS [get_ports DACData1_P[0]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[7]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[7]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[8]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[8]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[9]]   
set_property IOSTANDARD LVDS [get_ports DACData4_P[9]]   
set_property IOSTANDARD LVDS [get_ports DACData4_N[10]]  
set_property IOSTANDARD LVDS [get_ports DACData4_P[10]]  
set_property IOSTANDARD LVDS [get_ports DACData4_N[11]]  
set_property IOSTANDARD LVDS [get_ports DACData4_P[11]]  
set_property IOSTANDARD LVDS [get_ports DACCLK_N[3]]     
set_property IOSTANDARD LVDS [get_ports DACCLK_P[3]]        



# USB-UART Bridge (Silicon Labs CP2103GM)
################################################################################

set_property PACKAGE_PIN AU36 [get_ports USB_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RX]

set_property PACKAGE_PIN AU33 [get_ports USB_UART_TX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_TX]

# set_property PACKAGE_PIN AT32 [get_ports USB_UART_RTS]
# set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RTS]

set_property PACKAGE_PIN AR34 [get_ports USB_UART_CTS]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_CTS]


